### ISSUE TITLE
How many hours  did you take to train the baselines?

### ISSUE THREAD

**Issue by GoingMyWay** [deepmind/android_env#10]
Hi, in the paper, https://arxiv.org/pdf/2105.13231.pdf, 

![image](https://user-images.githubusercontent.com/9346460/120410732-204ec800-c386-11eb-98e5-54cb2bd7b66d.png)

In Figure 6, how many hours did you take to train the baselines?

**Comment by kenjitoyama** [comment]
Hello @GoingMyWay!

For these experiments we limited the interaction between the agent and the environment to 3/s, thus getting around `1e7/(3*60*60) ~= 926` actor-hours for every 10M steps. And to run these experiments in a reasonable time-frame, we used a distributed system to run 128 actors in parallel, thus taking just over 7 hours for every 10M steps.

I hope this answers your question.

Cheers,

Daniel

**Comment by GoingMyWay** [comment]
> Hello @GoingMyWay!
> 
> For these experiments we limited the interaction between the agent and the environment to 3/s, thus getting around `1e7/(3*60*60) ~= 926` actor-hours for every 10M steps. And to run these experiments in a reasonable time-frame, we used a distributed system to run 128 actors in parallel, thus taking just over 7 hours for every 10M steps.
> 
> I hope this answers your question.
> 
> Cheers,
> 
> Daniel

Thank you. If we speed the interaction time, maybe we can use less training time.

**Comment by kenjitoyama** [comment]
Hi! It'll take less time, but as we said in the paper the actual simulation will not go any faster, the agent will just get more observations and will send more actions in a given period, so for the same number of steps the simulation time will also decrease (which may be undesirable).

This is not a problem for apps that can react quickly and are not time sensitive (e.g. "press button" though that task has a time limit), but the behavior would be very different for the other ones (e.g. "rocket sleigh" or even "catch") if the agent interacts at 10 steps/s vs 1 step/s. For example, assume an episode in Catch takes approximately 10s, so if you let the agent step through the environment for 10K steps, you'd get 1K episodes at 1 step/s (with 1K non-zero rewards which are only given at the end of each episode) but only 100 episodes at 10 steps/s. Notice that moving the paddle faster doesn't necessarily give the agent any advantage, so it'll be significantly harder to learn at 10 steps/s due to credit assignment, exploration over much finer time scales and less data (0.1x the number of meaningful rewards).

Cheers!

Daniel

**Comment by GoingMyWay** [comment]
> Hi! It'll take less time, but as we said in the paper the actual simulation will not go any faster, the agent will just get more observations and will send more actions in a given period, so for the same number of steps the simulation time will also decrease (which may be undesirable).
> 
> This is not a problem for apps that can react quickly and are not time sensitive (e.g. "press button" though that task has a time limit), but the behavior would be very different for the other ones (e.g. "rocket sleigh" or even "catch") if the agent interacts at 10 steps/s vs 1 step/s. For example, assume an episode in Catch takes approximately 10s, so if you let the agent step through the environment for 10K steps, you'd get 1K episodes at 1 step/s (with 1K non-zero rewards which are only given at the end of each episode) but only 100 episodes at 10 steps/s. Notice that moving the paddle faster doesn't necessarily give the agent any advantage, so it'll be significantly harder to learn at 10 steps/s due to credit assignment, exploration over much finer time scales and less data (0.1x the number of meaningful rewards).
> 
> Cheers!
> 
> Daniel

Dear @kenjitoyama, thanks, I see.
