### ISSUE TITLE
I've modified some code to make it can run on the windows.

### ISSUE THREAD

**Issue by yizhangliu** [deepmind/android_env#16]
[android_env_for_windows](https://github.com/yizhangliu/android_env_for_windows)
Enjoy it.

**Comment by kenjitoyama** [comment]
Hello @yizhangliu!

As I have said in #14 , I believe the problem is simply that `pexpect` doesn't provide `pexpect.spawn` on Windows, and I have seen that that's exactly what you have done here: https://github.com/yizhangliu/android_env_for_windows/blob/main/android_env/components/adb_controller.py#L155. I believe that call should also work on Linux so we'd be able to remove that `sys` call switch.

The `checkStr` [here](https://github.com/yizhangliu/android_env_for_windows/blob/main/android_env/components/adb_controller.py#L105) is unnecessary as that's already covered by `self._prompt` which is customizable from the outside.

If you're looking to get your changes accepted, please open a pull request as in the current state, it's rather impossible for us to do anything about it. Thanks!

@a-gergely to comment more.
