### ISSUE TITLE
.textproto log_regexp syntax

### ISSUE THREAD

**Issue by yefremenko** [deepmind/android_env#22]
Hello. Thanks for your work.

I want to clarify the usage of `log_regexp` in `classic_2048.textproto` file. 
```
score: "^[Ss]core: ([-+]?[0-9]*\\.?[0-9]*)$"
```
However, in the console I see logs in a format: `score: 4.0`, which gives no match (but a string of `score 4.\0` matches with regexp). Why do we need `\\` in this regexp? Am I misunderstanding something?

I want to parse logs from my own apk.

**Comment by kenjitoyama** [comment]
Hello @yefremenko!

This is due to textprotos not having support for raw string literals. That is, we need one `\` for textprotos, then another `\` for Python to escape the `.`. In the end, the intended effect of the above regex is:

* `^` Beginning of the line
* `Score: ` or `score: `
* (optional) `-` or `+`
* 0 or more digits
* (optional) `.` char (but not any other character, which would be the case with a bare unescaped `.`)
* 0 or more digits
* `$` End of the line

Without escaping the `.`, we'd match something like `123a456`, `987#654` and so on, which we don't want.

To parse your own logs, you can pretty much copy the above regex in parentheses to match floating point numbers. You can also obviously customize the other parts of the pattern such as replacing "Score: " with something more appropriate for your situation.

If this works, please feel free to close the bug.

Thanks!

**Comment by yefremenko** [comment]
Thank you for the quick answer!
